# Permalinks
permalink:        pretty

# Setup
title:            Just Some Code
tagline:
description:      "I'm Cesar Aguirre. Software engineer. Lifelong learner"
url:              https://canro91.github.io
baseurl:          /

author:
  name:           'Cesar Aguirre'
  url:

paginate:         5

# Custom vars
version:

github:
  repo:           https://github.com/canro91

devto:            https://dev.to/canro91
linkedin:         https://linkedin.com/in/iamcesaraguirre

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll/tagging

tag_page_layout: tag_page
tag_page_dir: tag
