# Permalinks
permalink:        pretty

# Setup
title:            Just Some Code
tagline:
description:      "I'm Cesar Aguirre. Software engineer. Lifelong learner"
url:              https://canro91.github.io
baseurl:          /

author:
  name:           'Cesar Aguirre'
  url:

paginate:         5

# Custom vars
version:

github:
  repo:           https://github.com/canro91

plugins:
  - jekyll-paginate
  - jekyll-gist
